{
	"version": 1548583978,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/maxresdefault-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/firewatchforest-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/5a29d98c0b60d-sheet0.png",
		"images/newproject-sheet0.png",
		"images/tigerrock-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/kisspngtwigblackandwhitetree5af38619a6f-sheet0.png",
		"images/kisspngblackandwhitetreeeasternblackwalnutlovetree5aca5f5e5cdf-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/tiledbackground2.png",
		"images/sprite8-sheet0.png",
		"images/sprite8-sheet1.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/sprite9-sheet0.png",
		"images/tiledbackground3.png",
		"images/tipe1-sheet0.png",
		"images/tipbox-sheet0.png",
		"images/tipbox1-sheet0.png",
		"images/close-sheet0.png",
		"images/aladdin_abu_sheet-sheet0.png",
		"images/kisspngsweetgrassgrassescommonreed5b4d12ff29c-sheet0.png",
		"images/kisspngsweetgrassgrassescommonreed5b4d12ff29c2-sheet0.png",
		"images/rock-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite10-sheet1.png",
		"images/sprite10-sheet2.png",
		"images/sprite11-sheet0.png",
		"images/tiledbackground4.png",
		"images/sprite12-sheet0.png",
		"images/sprite12-sheet1.png",
		"images/sprite13-sheet0.png",
		"images/sprite13-sheet1.png",
		"images/sprite14-sheet0.png",
		"images/ropehdpngimagesofrope1181x-sheet0.png",
		"images/5a1d57465fef-sheet0.png",
		"images/kisspngtreestockphotographytrees5a6bbfc02d-sheet0.png",
		"images/tigertree-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/tiger-sheet0.png",
		"images/sprite16-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/sprite19-sheet1.png",
		"images/sprite20-sheet0.png",
		"images/tigerrock1-sheet0.png",
		"images/climbtree-sheet0.png",
		"images/sprite22-sheet0.png",
		"images/sprite23-sheet0.png",
		"images/mountain1-sheet0.png",
		"images/mountain2-sheet0.png",
		"images/dedrock-sheet0.png",
		"images/newproject2-sheet0.png",
		"images/zxz-sheet0.png",
		"images/sprite25-sheet0.png",
		"images/runm-sheet0.png",
		"images/spwnmonkey-sheet0.png",
		"images/sprite26-sheet0.png",
		"images/sp2-sheet0.png",
		"images/sprite27-sheet0.png",
		"images/sprock-sheet0.png",
		"images/banana-sheet0.png",
		"images/monkvisible-sheet0.png",
		"images/star-sheet0.png",
		"images/coingold-sheet0.png",
		"images/hudheart_full-sheet0.png",
		"images/mapbag-sheet0.png",
		"images/mapbag-sheet1.png",
		"images/sprite29-sheet0.png",
		"images/flagred-sheet0.png",
		"images/flagred-sheet1.png",
		"images/flagred-sheet2.png",
		"images/tipdes-sheet0.png",
		"images/sprite31-sheet0.png",
		"images/spritefont.png",
		"images/tree-sheet0.png",
		"images/gameover-sheet0.png",
		"images/sprite32-sheet0.png",
		"images/sprite33-sheet0.png",
		"images/sprite33-sheet1.png",
		"images/restart-sheet0.png",
		"images/tilemap.png",
		"images/tiledbackground5.png",
		"images/tiledbackground6.png",
		"images/sprite37-sheet0.png",
		"images/sprite37-sheet1.png",
		"images/sprite37-sheet2.png",
		"images/sprite38-sheet0.png",
		"images/sprite38-sheet1.png",
		"images/sprite38-sheet2.png",
		"images/28292555279_04b3433834_b-sheet0.png",
		"images/sprit5-sheet0.png",
		"images/spwnthief-sheet0.png",
		"images/sprit17-sheet0.png",
		"images/tiledbackground8.png",
		"images/vlc-sheet0.png",
		"images/sprit11-sheet0.png",
		"images/visiblet1-sheet0.png",
		"images/sprit16-sheet0.png",
		"images/sprit8-sheet0.png",
		"images/sprit10-sheet0.png",
		"images/visibletip-sheet0.png",
		"images/dog2-sheet0.png",
		"images/dog2-sheet1.png",
		"images/sprit15-sheet0.png",
		"images/fly-sheet0.png",
		"images/dustbin.png",
		"images/thief-sheet0.png",
		"images/thief-sheet1.png",
		"images/sprit14-sheet0.png",
		"images/sprit18-sheet0.png",
		"images/player2-sheet0.png",
		"images/home-sheet0.png",
		"images/sprit26-sheet0.png",
		"images/smoke-sheet0.png",
		"images/thewaytohome-sheet0.png",
		"images/tiledbackground9.png",
		"images/sprite40-sheet0.png",
		"images/play_alt-sheet0.png",
		"images/sprite41-sheet0.png",
		"images/pop-sheet0.png",
		"images/sprite42-sheet0.png",
		"images/vs1-sheet0.png",
		"images/last-sheet0.png",
		"images/ll-sheet0.png",
		"media/316467__littlerobotsoundfactory__human-good-18.ogg",
		"media/316468__littlerobotsoundfactory__human-good-17.ogg",
		"media/animals_alligator_hiss_002.ogg",
		"media/audio_hero_birdsscandinavia_digic13_71_330.ogg",
		"media/audio_hero_houseresidential_digivb1_57_375.ogg",
		"media/bite+1.ogg",
		"media/ftus_animals_dog_bark_med_003_245.ogg",
		"media/gain_walkers_cicada_close_up_short_cricket_like_trill.ogg",
		"media/pain-soundbible.com-1883168362-1883168362.ogg",
		"media/scream+3.ogg",
		"media/video_game_splash-ploor-699235037.ogg",
		"media/water-lisa_redfern-1888623835.ogg",
		"media/click.m4a",
		"media/click.ogg",
		"media/collect gem.m4a",
		"media/collect gem.ogg",
		"media/collect key.m4a",
		"media/collect key.ogg",
		"media/enemyhit.m4a",
		"media/enemyhit.ogg",
		"media/fall and splat-soundbible.com-1428277441.ogg",
		"media/funny-game-over-sound.ogg",
		"media/hit.m4a",
		"media/hit.ogg",
		"media/idea-sound-effect.ogg",
		"media/jingle lose.m4a",
		"media/jingle lose.ogg",
		"media/jingle win.m4a",
		"media/jingle win.ogg",
		"media/mattoglseby - 1.m4a",
		"media/mattoglseby - 1.ogg",
		"media/planning-heists-in-83 (1).ogg",
		"media/twitter-notification-sound.ogg",
		"media/dog growl then bark-soundbible.com-224495057.m4a",
		"media/dog growl then bark-soundbible.com-224495057.ogg",
		"media/tiger growling-soundbible.com-258880045.m4a",
		"media/tiger growling-soundbible.com-258880045.ogg",
		"media/lion roar-soundbible.com-718441804.m4a",
		"media/lion roar-soundbible.com-718441804.ogg",
		"media/monkeys monkeying around-soundbible.com-1738007729.m4a",
		"media/monkeys monkeying around-soundbible.com-1738007729.ogg",
		"media/street-daniel_simon.m4a",
		"media/street-daniel_simon.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}